version: '3.8'
services:
  tinyproxy:
    image: docker.io/kalaksi/tinyproxy:latest
    restart: unless-stopped
    cap_drop:
    - ALL
    ports:
    - ${TINYPROXY_PORT}:8888
    environment:
      DISABLE_VIA_HEADER: 'yes'
      STAT_HOST: tinyproxy.stats
      MAX_CLIENTS: 100
      ALLOWED_NETWORKS: 0.0.0.0/0
      LOG_LEVEL: Notice
      TIMEOUT: 900
      AUTH_USER: ${TINYPROXY_AUTH_USER}
      AUTH_PASSWORD: ${TINYPROXY_AUTH_PASSWORD}
    healthcheck:
      test: ["CMD", "curl", "-I", "-H", "Host: tinyproxy.stats", "http://localhost:8888"]
  ja3-proxy:
    image: xyhelper/ja3-proxy:latest
    ports:
    - ${JA3_PROXY_PORT}:9988
    environment:
      WEBSITE_URL: ${WEBSITE_URL}
      PROXY: http://${TINYPROXY_AUTH_USER}:${TINYPROXY_AUTH_PASSWORD}@${REAL_IP}:${TINYPROXY_PORT}
      CLIENTKEY: ${CLIENTKEY}
      LOCALPROXYUSER: ${JA3_PROXY_AUTH_USER}
      LOCALPROXYPASS: ${JA3_PROXY_AUTH_PASSWORD}
